import type { GameCard } from "./game"

// Advanced deck with new cards and effects
export const ADVANCED_DECK: GameCard[] = [
  // Terrestrial Animals
  {
    id: 101,
    type: "animal",
    name: "Mouse",
    points: 1,
    environment: "terrestrial",
    effect: "On play, send a terrestrial or amphibian animal your opponent controls to deck top.",
    imageUrl: "/forest-mouse-foraging.png",
  },
  {
    id: 102,
    type: "animal",
    name: "Squirrel",
    points: 1,
    environment: "terrestrial",
    effect: "On play, look at your opponent's hand and select a card to be discarded.",
    imageUrl: "/bushy-tailed-perch.png",
  },
  {
    id: 103,
    type: "animal",
    name: "Fox",
    points: 2,
    environment: "terrestrial",
    effect: "On play, your opponent discards a card at random.",
    imageUrl: "/alert-fox.png",
  },
  {
    id: 104,
    type: "animal",
    name: "Snake",
    points: 2,
    environment: "terrestrial",
    effect: "On play, destroy an animal of 1 point your opponent controls.",
    imageUrl: "/coiled-grass-snake.png",
  },
  {
    id: 105,
    type: "animal",
    name: "Zebra",
    points: 3,
    environment: "terrestrial",
    effect: "On play, look at your opponent's hand.",
    imageUrl: "/savanna-zebra.png",
  },
  {
    id: 106,
    type: "animal",
    name: "Deer",
    points: 3,
    environment: "terrestrial",
    effect: "On play, if you have 7 or more points, your opponent discards 1 card at random.",
    imageUrl: "/forest-deer.png",
  },
  {
    id: 107,
    type: "animal",
    name: "Wolf",
    points: 3,
    environment: "terrestrial",
    effect:
      "On play, if your opponent has 5 or fewer cards in hand, send 1 terrestrial animal they control to their hand.",
    imageUrl: "/lone-howler.png",
  },
  {
    id: 108,
    type: "animal",
    name: "Lion",
    points: 4,
    environment: "terrestrial",
    effect: "Sacrifice 1 animal to play this card. On play, your opponent discards 2 cards at random.",
    imageUrl: "/savanna-king.png",
  },
  // Aquatic Animals
  {
    id: 109,
    type: "animal",
    name: "Tuna",
    points: 1,
    environment: "aquatic",
    effect: "On play, play an aquatic or amphibian animal of 3 or fewer points from hand.",
    imageUrl: "/canned-tuna-stack.png",
  },
  {
    id: 110,
    type: "animal",
    name: "Seahorse",
    points: 1,
    environment: "aquatic",
    effect: "On play, draw 1 card for every animal you played this turn.",
    imageUrl: "/camouflaged-seahorse.png",
  },
  {
    id: 111,
    type: "animal",
    name: "Jellyfish",
    points: 2,
    environment: "aquatic",
    effect: "On play, draw 1 card.",
    imageUrl: "/bioluminescent-jelly.png",
  },
  {
    id: 112,
    type: "animal",
    name: "Turtle",
    points: 2,
    environment: "aquatic",
    effect: "On play, play an aquatic or amphibian animal of 2 or fewer points from hand.",
    imageUrl: "/serene-sea-turtle.png",
  },
  {
    id: 113,
    type: "animal",
    name: "Dolphin",
    points: 3,
    environment: "aquatic",
    effect: "On play, you may send 1 card from hand to deck bottom to draw 1 card.",
    imageUrl: "/playful-dolphin.png",
  },
  {
    id: 114,
    type: "animal",
    name: "Octopus",
    points: 3,
    environment: "aquatic",
    effect: "On play, look at the top 3 cards of the deck.",
    imageUrl: "/curious-octopus.png",
  },
  {
    id: 115,
    type: "animal",
    name: "Stingray",
    points: 3,
    environment: "aquatic",
    effect: "On play, if you have 7 or more points, draw 1 card.",
    imageUrl: "/graceful-glider.png",
  },
  {
    id: 116,
    type: "animal",
    name: "Shark",
    points: 4,
    environment: "aquatic",
    effect: "Sacrifice 1 animal to play this card. On play, draw cards until you have 4.",
    imageUrl: "/reef-shark-patrol.png",
  },
  // Amphibian Animals
  {
    id: 117,
    type: "animal",
    name: "Frog",
    points: 1,
    environment: "amphibian",
    effect: "On play, send the animal with the lowest points your opponent controls to the deck bottom.",
    imageUrl: "/serene-frog.png",
  },
  {
    id: 118,
    type: "animal",
    name: "Crab",
    points: 2,
    environment: "amphibian",
    effect: "On play, look at the top 2 cards: add 1 to hand and send the other to deck bottom.",
    imageUrl: "/beach-crab-close-up.png",
  },
  {
    id: 119,
    type: "animal",
    name: "Otter",
    points: 3,
    environment: "amphibian",
    effect: "On play, if you have 7 or more points, take a random card from your opponent's hand.",
    imageUrl: "/playful-river-otter.png",
  },
  {
    id: 120,
    type: "animal",
    name: "Crocodile",
    points: 4,
    environment: "amphibian",
    effect:
      "Sacrifice 1 animal to play this card. On play, send 1 animal of 3 or fewer points your opponent controls to deck bottom.",
    imageUrl: "/swamp-crocodile.png",
  },
  // Impact Cards
  {
    id: 121,
    type: "impact",
    name: "Hunter",
    effect: "Destroy 1 terrestrial animal.",
    imageUrl: "/vigilant-watcher.png",
  },
  {
    id: 122,
    type: "impact",
    name: "Fisher",
    effect: "Destroy 1 aquatic animal.",
    imageUrl: "/weathered-net-caster.png",
  },
  // Removed Scare card (ID 123)
  {
    id: 124,
    type: "impact",
    name: "Veterinarian",
    effect: "Play an animal from discard.",
    imageUrl: "/compassionate-vet-care.png",
  },
  {
    id: 125,
    type: "impact",
    name: "Confuse",
    effect: "Exchange control between 2 animals.",
    imageUrl: "/bewildered-critters.png",
  },
  {
    id: 126,
    type: "impact",
    name: "Domesticate",
    effect: "Gain control over an animal of 2 points.",
    imageUrl: "/farm-friends.png",
  },
  {
    id: 127,
    type: "impact",
    name: "Epidemic",
    effect: "Send 1 animal you control and all animals of same environment to deck bottom.",
    imageUrl: "/interconnected-disease-spread.png",
  },
  {
    id: 128,
    type: "impact",
    name: "Compete",
    effect: "Discard 1 animal to send all animals of same points to deck bottom.",
    imageUrl: "/cheetah-gazelle-chase.png",
  },
  {
    id: 129,
    type: "impact",
    name: "Prey",
    effect: "Select 1 animal on your field: send all other animals of same environment and fewer points to the bottom.",
    imageUrl: "/stealthy-stalker.png",
  },
  {
    id: 130,
    type: "impact",
    name: "Earthquake",
    effect: "Send all animals worth 3 or more points to deck bottom.",
    imageUrl: "/shattered-cityscape.png",
  },
  // Added Flood card
  {
    id: 131,
    type: "impact",
    name: "Flood",
    effect: "Each player sends their 2 smallest animals to deck bottom (random if tied).",
    imageUrl: "/flooded-street-city.png",
  },
  // Added Trap card
  {
    id: 132,
    type: "impact",
    name: "Trap",
    effect: "Your opponent gives you one of their animals.",
    imageUrl: "/hidden-pitfall.png",
  },
  // Added Cage card
  {
    id: 133,
    type: "impact",
    name: "Cage",
    effect: "Send 1 animal from your field to the discard pile to gain control of an opponent's animal.",
    imageUrl: "/bird-in-ornate-cage.png",
  },
  // Added Limit card
  {
    id: 134,
    type: "impact",
    name: "Limit",
    effect:
      "Destroy 1 animal your opponent controls. Your opponent can't play more than 1 animal per turn for 2 turns.",
    imageUrl: "/limit-art.png",
  },
  // Added Storm card
  {
    id: 135,
    type: "impact",
    name: "Storm",
    effect: "Send all animals worth 2 or fewer points to deck bottom.",
    imageUrl: "/storm-art.png",
  },
  // Added Drought card
  {
    id: 136,
    type: "impact",
    name: "Drought",
    effect: "Each player sends animals to the bottom until they have 2.",
    imageUrl: "/drought-art.png",
  },
  // Added Flourish card
  {
    id: 137,
    type: "impact",
    name: "Flourish",
    effect: "If you have 2 or fewer cards in hand, draw until you have 6.",
    imageUrl: "/flourish-art.png",
  },
]
