import type { GameCard } from "./game"

// Original deck cards
export const ORIGINAL_DECK: GameCard[] = [
  // Terrestrial Animals
  {
    id: 1,
    type: "animal",
    name: "Lion",
    points: 4,
    environment: "terrestrial",
    effect: "On play, destroy an animal your opponent controls.",
    imageUrl: "/majestic-lion-portrait.png",
  },
  {
    id: 2,
    type: "animal",
    name: "Mouse",
    points: 1,
    environment: "terrestrial",
    effect: "On play, draw a card.",
    imageUrl: "/field-mouse-close-up.png",
  },
  {
    id: 3,
    type: "animal",
    name: "Snake",
    points: 2,
    environment: "terrestrial",
    effect: "On play, your opponent discards a card.",
    imageUrl: "/coiled-python.png",
  },

  // Aquatic Animals
  {
    id: 4,
    type: "animal",
    name: "Dolphin",
    points: 3,
    environment: "aquatic",
    effect: "On play, look at the top 3 cards of the deck and rearrange them.",
    imageUrl: "/playful-dolphin-pod.png",
  },
  {
    id: 5,
    type: "animal",
    name: "Fish",
    points: 1,
    environment: "aquatic",
    effect: "On play, draw a card if you control another aquatic animal.",
    imageUrl: "/coral-reef-life.png",
  },
  {
    id: 6,
    type: "animal",
    name: "Octopus",
    points: 3,
    environment: "aquatic",
    effect: "On play, look at your opponent's hand.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=octopus",
  },

  // Amphibian Animals
  {
    id: 7,
    type: "animal",
    name: "Frog",
    points: 1,
    environment: "amphibian",
    effect: "On play, return an animal with 2 or fewer points to its owner's hand.",
    imageUrl: "/green-leaf-frog.png",
  },
  {
    id: 8,
    type: "animal",
    name: "Crab",
    points: 2,
    environment: "amphibian",
    effect: "On play, draw a card if you have fewer cards in hand than your opponent.",
    imageUrl: "/hermit-crab-shell.png",
  },
  {
    id: 9,
    type: "animal",
    name: "Otter",
    points: 3,
    environment: "amphibian",
    effect: "On play, you may play an additional animal this turn.",
    imageUrl: "/playful-otter-river.png",
  },
  {
    id: 10,
    type: "animal",
    name: "Crocodile",
    points: 4,
    environment: "amphibian",
    effect: "On play, destroy an animal with 3 or fewer points.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=crocodile",
  },

  // Impact Cards
  {
    id: 11,
    type: "impact",
    name: "Hunter",
    effect: "Destroy a terrestrial animal.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=hunter",
  },
  {
    id: 12,
    type: "impact",
    name: "Fisher",
    effect: "Destroy an aquatic animal.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=fisher",
  },
  {
    id: 13,
    type: "impact",
    name: "Drought",
    effect: "All players discard an aquatic animal from their field.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=drought",
  },
  {
    id: 14,
    type: "impact",
    name: "Flood",
    effect: "All players discard a terrestrial animal from their field.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=flood",
  },
  {
    id: 15,
    type: "impact",
    name: "Trap",
    effect: "Destroy an animal with 2 or fewer points.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=trap",
  },
  {
    id: 16,
    type: "impact",
    name: "Cage",
    effect: "An animal cannot attack until your next turn.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=cage",
  },
  {
    id: 17,
    type: "impact",
    name: "Scare",
    effect: "Return an animal to its owner's hand.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=scare",
  },
  {
    id: 18,
    type: "impact",
    name: "Confuse",
    effect: "Exchange control of two animals with 2 or fewer points.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=confuse",
  },
  {
    id: 19,
    type: "impact",
    name: "Domesticate",
    effect: "Gain control of an animal with 1 point.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=domesticate",
  },
  {
    id: 20,
    type: "impact",
    name: "Release",
    effect: "Return an animal you control to your hand, then draw a card.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=release",
  },
  {
    id: 21,
    type: "impact",
    name: "Compete",
    effect: "Each player sacrifices their animal with the lowest points.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=compete",
  },
  {
    id: 22,
    type: "impact",
    name: "Prey",
    effect: "Destroy an animal with the lowest points on the field.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=prey",
  },
  {
    id: 23,
    type: "impact",
    name: "Flourish",
    effect: "Draw two cards.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=flourish",
  },
  {
    id: 24,
    type: "impact",
    name: "Earthquake",
    effect: "All players sacrifice a terrestrial animal.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=earthquake",
  },
  {
    id: 25,
    type: "impact",
    name: "Storm",
    effect: "All players sacrifice an aquatic animal.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=storm",
  },
  {
    id: 26,
    type: "impact",
    name: "Epidemic",
    effect: "All animals lose their abilities until the end of the turn.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=epidemic",
  },
  {
    id: 27,
    type: "impact",
    name: "Limit",
    effect: "Players cannot play more than one animal per turn until your next turn.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=limit",
  },
  {
    id: 28,
    type: "impact",
    name: "Veterinarian",
    effect: "Return an animal from your discard pile to your hand.",
    imageUrl: "/placeholder.svg?height=120&width=80&query=veterinarian",
  },
]
